### ISSUE TITLE
Have been looking for a solution like that

### ISSUE THREAD

**Issue by MaBecker** [Jonathan-Chandler/beaglebone-ws2812b#1]
Hi,

thanks for sharing your work, will give a try over the weekend.

All the other solution are too overloaded to my use case:

- up to two strips with up to 600 leds
- just turn some ranges on and off

KR Mark

**Comment by Jonathan-Chandler** [comment]
Hi Mark, 

I just now noticed your comment, hopefully modifying the solution for 1200 leds worked for you.

There's a second branch with more readable code and a color cycling feature that you can pull from the led-tdd-rework branch if you're interested.

**Comment by MaBecker** [comment]
Hi Jonathan,

thanks for you response,  yes I looked into  both branches and tried to get  `led-tdd-rework` working for me. It is not working for me yet, because the board setup is missing pwm ports. 

Just fetched the upstream. Nice you did some rework  for branch led-tdd-rework - thanks. Now make can build test/main.out and leds without issues.

**Comment by MaBecker** [comment]
running on a bbb with 4.19.94-ti-r64a and those active uEnt.txt lines:

```bash
grep ^[^#] /boot/uEnv.txt 
uname_r=4.19.94-ti-r64
dtb=am335x-boneblack.dtb
enable_uboot_overlays=1
enable_uboot_cape_universal=1
uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-19-TI-00A0.dtbo
cmdline=coherent_pool=1M net.ifnames=0 quiet
```

Can you please share your setup?

**Comment by Jonathan-Chandler** [comment]
Thanks, I didn't notice the missing pwm configure script. It's on the tdd branch now and added to buildrun.sh

My uEnv is similar:
uname_r=4.19.94-ti-r42
enable_uboot_overlays=1
uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-19-TI-00A0.dtbo
enable_uboot_cape_universal=1
cmdline=coherent_pool=1M net.ifnames=0 lpj=1990656 rng_core.default_quality=100 quiet

Can I ask what you're building with the 600 leds?

**Comment by MaBecker** [comment]
> Can I ask what you're building with the 600 leds?

Sure, think of anything with many compartments like a shelf and you like to switch on some pixel to highlight one or more  sections.

**Comment by Jonathan-Chandler** [comment]
Sounds like an interesting project, post pictures of the end result even if you don't end up using any of this code.
